---
- name: Remove stale grafana container if exists
  shell: docker rm -f grafana prometheus ryu_exporter || true

- name: Ensure monitoring stack is started
  shell: docker-compose up -d --build
  args:
    chdir: "{{ playbook_dir }}/.."
  register: monitoring_result
  failed_when: monitoring_result.rc != 0

- name: Show monitoring deployment result
  debug:
    msg: "{{ monitoring_result.stdout_lines }}"