version: "3.8"

services:
  ryu_exporter:
    build:
      context: .
      dockerfile: docker/Dockerfile.exporter
    container_name: ryu_exporter
    environment:
      - RYU_STATS_URL=http://sdn-controller:8080/stats/port/ALL
    ports:
      - "8000:8000"
    networks:
      - sdn_net
    restart: unless-stopped

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml:ro
      # 👇 1. AJOUTE CECI : Sauvegarde l'historique des métriques
      - prometheus_data:/prometheus 
    ports:
      - "9090:9090"
    networks:
      - sdn_net
    restart: unless-stopped

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000"
    volumes:
      # 👇 2. AJOUTE CECI : Sauvegarde tes Dashboards et Data Sources
      - grafana_data:/var/lib/grafana 
    networks:
      - sdn_net
    restart: unless-stopped

networks:
  sdn_net:
    external: true

# 👇 3. AJOUTE CE BLOC TOUT EN BAS : Déclaration des disques durs virtuels
volumes:
  grafana_data:
  prometheus_data: