- name: ⏳ Attendre que Mininet connecte tous les switchs
  ansible.builtin.pause:
    seconds: 30
- name: Add ICMP drop rule
  uri:
    url: "http://127.0.0.1:8080/firewall/rules/{{ item }}"
    method: POST
    body_format: json
    body:
      priority: 100
      dl_type: "IPv4"
      nw_proto: "ICMP"
      actions: "DENY"  # <-- C'est ce qui manquait pour éviter l'erreur 400
    status_code: 200
  loop:
    - "0000000000000001"
    - "0000000000000002"
    - "0000000000000003"
- name: Allow all other IPv4 traffic (TCP/UDP)
  uri:
    url: "http://127.0.0.1:8080/firewall/rules/{{ item }}"
    method: POST
    body_format: json
    body:
      priority: 10          # Priorité basse (10 < 100 de ton ICMP)
      dl_type: "IPv4"
      actions: "ALLOW"      # On autorise le reste
    status_code: 200
  loop:
    - "0000000000000001"
    - "0000000000000002"
    - "0000000000000003"
- name: Allow ARP traffic (Indispensable pour la découverte MAC)
  uri:
    url: "http://127.0.0.1:8080/firewall/rules/{{ item }}"
    method: POST
    body_format: json
    body:
      priority: 10          # Même priorité basse que IPv4
      dl_type: "ARP"
      actions: "ALLOW"      # On autorise l'ARP
    status_code: 200
  loop:
    - "0000000000000001"
    - "0000000000000002"
    - "0000000000000003"
- name: Enable Firewall module on switches
  uri:
    url: "http://127.0.0.1:8080/firewall/module/enable/{{ item }}"
    method: PUT
    status_code: 200
  loop:
    - "0000000000000001"
    - "0000000000000002"
    - "0000000000000003"
