- name: 🧹 Nettoyer l'environnement Mininet précédent
  shell: mn -c
  become: yes
  ignore_errors: yes

- name: 🧪 Lancer la Topologie et exécuter les tests réseau automatisés
  shell: python3 {{ playbook_dir }}/../tests/network_tests.py
  become: yes
  register: test_results

- name: 📊 Afficher les résultats des tests dans Ansible
  debug:
    msg: "{{ test_results.stdout_lines }}"
