# Fichier: .github/workflows/pipeline.yml
name: SDN NetDevOps Pipeline

on:
  push:
    branches: [ main ]

jobs:
  sdn-pipeline:
    runs-on: self-hosted   

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v3

      - name: 🔍 Vérifier la syntaxe JSON (Tests CI)
        run: |
          python3 -m json.tool controller/policies/firewall.json > /dev/null
          python3 -m json.tool controller/policies/qos.json > /dev/null
          python3 -m py_compile scripts/deploy_policies.py

      - name: 🐳 Build Docker Image (Ryu)
        run: docker build -t mon-ryu ./docker

      - name: 🚀 Update Infrastructure with Ansible
        run: ansible-playbook ansible/deploy.yml -i ansible/inventory.ini

      - name: ⚡ Déployer les règles (Firewall & QoS) dynamiquement
        run: |
          echo "Injection des nouvelles politiques dans le contrôleur..."
          python3 scripts/deploy_policies.py
          echo "✅ Mise à jour terminée sans couper le Datacenter !"